apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: wapwrap
  name: wapwrap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wapwrap
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: wapwrap
    spec:
      containers:
        - image: wapwrap:latest
          name: wapwrap
          ports:
            - containerPort: 8080
          resources: {}
        - image: wapwrap-sentimentservice:nzzy43uyy2tiyhqa
          name: wapwrap-sentimentservice
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
